(source melpa)

(depends-on "pallet")
(depends-on "solarized-theme")
(depends-on "powerline")

(depends-on "evil")

(depends-on "projectile")
(depends-on "flx-ido")
(depends-on "smex")
(depends-on "etags-select")

(depends-on "phi-search")
(depends-on "multiple-cursors")

(depends-on "smart-tab")
(depends-on "smartparens")

(depends-on "rbenv")
(depends-on "rspec-mode")

(depends-on "coffee-mode")

(depends-on "magit")
(depends-on "gitconfig-mode")
(depends-on "gitignore-mode")

(depends-on "jabber")

(depends-on "markdown-mode")
